import { Ad, UserProfile, Category } from '../types';

export const MOCK_PROFESSIONALS: UserProfile[] = [
  {
    uid: 'pro1',
    username: 'mestre_obra',
    displayName: 'Carlos Alvenaria',
    password: '12345',
    role: 'professional',
    status: 'approved',
    photoURL: 'https://images.pexels.com/photos/585419/pexels-photo-585419.jpeg?auto=compress&cs=tinysrgb&w=150',
    description: 'Mestre de obras com 20 anos de experiência em estruturas de concreto e alvenaria estrutural.',
    rating: 4.9,
    reviewCount: 45,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 365,
    plan: 'premium',
    phone: '(11) 98888-7777',
    whatsapp: '5511988887777',
    instagram: 'carlos_alvenaria_pro',
    location: 'São Paulo, SP - Zona Sul',
    skills: ['Alvenaria Estrutural', 'Leitura de Projetos', 'Gestão de Equipes', 'Fundações'],
    portfolio: [
      {
        id: 'p1',
        userId: 'pro1',
        title: 'Fundação Residencial Alphaville',
        description: 'Execução completa de fundação e estrutura para casa de alto padrão.',
        images: [
          'https://images.pexels.com/photos/159358/construction-site-build-construction-work-159358.jpeg?auto=compress&cs=tinysrgb&w=800',
          'https://images.pexels.com/photos/159306/construction-site-build-construction-work-159306.jpeg?auto=compress&cs=tinysrgb&w=800'
        ],
        rating: 5.0,
        reviewCount: 12,
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
      }
    ]
  },
  {
    uid: 'pro2',
    username: 'eletrica_pro',
    displayName: 'Ricardo Eletricista',
    password: '12345',
    role: 'professional',
    category: 'Elétrica',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=150&h=150&auto=format&fit=crop',
    description: 'Especialista em instalações elétricas residenciais e industriais. Certificado NR10.',
    rating: 4.8,
    reviewCount: 32,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 200,
    plan: 'free',
    portfolio: [
      {
        id: 'p2',
        userId: 'pro2',
        title: 'Quadro de Força Industrial',
        description: 'Montagem e organização de quadro trifásico.',
        images: ['https://images.unsplash.com/photo-1460518451285-cd7ba71ba515?q=80&w=800&h=600&auto=format&fit=crop'],
        rating: 4.9,
        reviewCount: 5,
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
      }
    ]
  },
  {
    uid: 'pro3',
    username: 'pintura_arte',
    displayName: 'Marcos Pinturas',
    password: '12345',
    role: 'professional',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=150&h=150&auto=format&fit=crop',
    description: 'Pintura decorativa, aplicação de textura e grafiato. Acabamento fino.',
    rating: 4.7,
    reviewCount: 28,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 150,
    plan: 'premium',
  },
  {
    uid: 'pro4',
    username: 'gesso_design',
    displayName: 'Fabiano Gesseiro',
    password: '12345',
    role: 'professional',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1590650153855-d9e808231d41?q=80&w=150&h=150&auto=format&fit=crop',
    description: 'Sancas, forros de drywall e molduras personalizadas.',
    rating: 4.9,
    reviewCount: 19,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 80,
    portfolio: [
      {
        id: 'p4',
        userId: 'pro4',
        title: 'Forro de Drywall com Iluminação',
        description: 'Instalação de forro de drywall com sancas invertidas e iluminação em LED.',
        images: [
          'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?q=80&w=800&h=600&auto=format&fit=crop',
          'https://images.unsplash.com/photo-1503387762-592dee58c460?q=80&w=800&h=600&auto=format&fit=crop'
        ],
        rating: 5.0,
        reviewCount: 8,
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 15,
      }
    ]
  },
  {
    uid: 'pro5',
    username: 'hidraulica_express',
    displayName: 'José Encanador',
    role: 'professional',
    category: 'Hidráulica',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1585704032915-c3400ca1f963?q=80&w=150&h=150&auto=format&fit=crop',
    description: 'Caça vazamentos e instalações hidráulicas completas.',
    rating: 4.6,
    reviewCount: 15,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 60,
  },
  {
    uid: 'pro6',
    username: 'sergio_telhados',
    displayName: 'Sérgio Telhados',
    role: 'professional',
    status: 'approved',
    photoURL: 'https://images.pexels.com/photos/1216589/pexels-photo-1216589.jpeg?auto=compress&cs=tinysrgb&w=150',
    description: 'Especialista em telhados coloniais, limpeza de calhas e impermeabilização de lajes.',
    rating: 4.8,
    reviewCount: 22,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 120,
    portfolio: [
      {
        id: 'p6',
        userId: 'pro6',
        title: 'Reforma de Telhado Colonial',
        description: 'Troca completa de telhas e reforço de estrutura em madeira.',
        images: [
          'https://images.pexels.com/photos/3829227/pexels-photo-3829227.jpeg?auto=compress&cs=tinysrgb&w=800',
          'https://images.pexels.com/photos/2091166/pexels-photo-2091166.jpeg?auto=compress&cs=tinysrgb&w=800'
        ],
        rating: 4.9,
        reviewCount: 7,
        createdAt: Date.now() - 1000 * 60 * 60 * 24 * 20,
      }
    ]
  },
  {
    uid: 'pro12',
    username: 'calhas_master',
    displayName: 'Roberto Calhas',
    role: 'professional',
    status: 'approved',
    photoURL: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150',
    description: 'Instalação e limpeza de calhas, rufos e condutores em alumínio e galvanizado.',
    rating: 4.7,
    reviewCount: 12,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 150,
  },
  {
    uid: 'pro7',
    username: 'andre_pisos',
    displayName: 'André Revestimentos',
    role: 'professional',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=150&h=150&auto=format&fit=crop',
    description: 'Colocação de porcelanato, cerâmica e pedras decorativas com nivelamento perfeito.',
    rating: 4.9,
    reviewCount: 37,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 250,
  },
  {
    uid: 'pro8',
    username: 'luiz_marcenaria',
    displayName: 'Luiz Marceneiro',
    role: 'professional',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=150&h=150&auto=format&fit=crop',
    description: 'Móveis planejados de alto padrão, cozinhas, dormitórios e home office.',
    rating: 4.7,
    reviewCount: 18,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 90,
  },
  {
    uid: 'pro13',
    username: 'metal_art',
    displayName: 'Marcos Serralheiro',
    role: 'professional',
    status: 'approved',
    photoURL: 'https://images.pexels.com/photos/2219024/pexels-photo-2219024.jpeg?auto=compress&cs=tinysrgb&w=150',
    description: 'Serralheria artística, portões basculantes, grades de proteção e estruturas metálicas.',
    rating: 4.8,
    reviewCount: 15,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 60,
  },
  {
    uid: 'pro14',
    username: 'tec_edificacao',
    displayName: 'Juliana Técnica',
    role: 'professional',
    status: 'approved',
    photoURL: 'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=150',
    description: 'Técnica em Edificações com foco em regularização de imóveis, plantas e acompanhamento de obra.',
    rating: 4.9,
    reviewCount: 24,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 180,
  },
  {
    uid: 'pro9',
    username: 'arq_fernanda',
    displayName: 'Arq. Fernanda G.',
    role: 'professional',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=150&h=150&auto=format&fit=crop',
    description: 'Projetos arquitetônicos, design de interiores e acompanhamento de obras.',
    rating: 5.0,
    reviewCount: 14,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 300,
  },
  {
    uid: 'pro10',
    username: 'limpeza_brilho',
    displayName: 'Limpeza Brilho Total',
    role: 'professional',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1584820927498-cfe5211ff973?q=80&w=150&h=150&auto=format&fit=crop',
    description: 'Equipe especializada em limpeza pós-obra pesada e higienização.',
    rating: 4.5,
    reviewCount: 41,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 45,
  },
  {
    uid: 'pro11',
    username: 'geraldo_faztudo',
    displayName: 'Geraldo Faz-Tudo',
    role: 'professional',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=150&h=150&auto=format&fit=crop',
    description: 'Pequenos reparos, montagem de móveis e manutenção geral.',
    rating: 4.6,
    reviewCount: 52,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 400,
  },
  {
    uid: 'pro15',
    username: 'marcos_armador',
    displayName: 'Marcos Armador',
    role: 'professional',
    status: 'approved',
    photoURL: 'https://images.pexels.com/photos/159306/construction-site-build-construction-work-159306.jpeg?auto=compress&cs=tinysrgb&w=150',
    description: 'Especialista em armação de ferragens para vigas, colunas e sapatas.',
    rating: 4.8,
    reviewCount: 19,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 120,
  },
  {
    uid: 'pro16',
    username: 'pedro_ajudante',
    displayName: 'Pedro Ajudante',
    role: 'professional',
    category: 'Ajudante',
    helperSpecialty: 'ajudante de pedreiro',
    status: 'approved',
    photoURL: 'https://images.pexels.com/photos/159358/construction-site-build-construction-work-159358.jpeg?auto=compress&cs=tinysrgb&w=150',
    description: 'Ajudante geral experiente, auxílio em alvenaria, carga e descarga de materiais e limpeza.',
    rating: 4.7,
    reviewCount: 12,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
  }
];

export const MOCK_CLIENTS: UserProfile[] = [
  {
    uid: 'cli1',
    username: 'arq_ana',
    displayName: 'Ana Arquiteta',
    password: '12345',
    role: 'client',
    clientType: 'architect',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=150&h=150&auto=format&fit=crop',
    description: 'Escritório de arquitetura focado em interiores residenciais.',
    rating: 5.0,
    reviewCount: 10,
    createdAt: Date.now(),
    plan: 'premium',
  },
  {
    uid: 'cli2',
    username: 'eng_bruno',
    displayName: 'Bruno Engenheiro',
    role: 'client',
    clientType: 'engineer',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=150&h=150&auto=format&fit=crop',
    description: 'Cálculo estrutural e acompanhamento de obras.',
    rating: 4.9,
    reviewCount: 8,
    createdAt: Date.now(),
    plan: 'free',
  },
  {
    uid: 'cli3',
    username: 'imob_centro',
    displayName: 'Imobiliária Central',
    role: 'client',
    clientType: 'real_estate',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=150&h=150&auto=format&fit=crop',
    description: 'Gestão de reformas para imóveis de locação.',
    rating: 4.5,
    reviewCount: 25,
    createdAt: Date.now(),
  },
  {
    uid: 'cli4',
    username: 'cliente_final1',
    displayName: 'Roberto Silva',
    role: 'client',
    clientType: 'final_client',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=150&h=150&auto=format&fit=crop',
    description: 'Proprietário realizando reforma em casa própria.',
    rating: 4.8,
    reviewCount: 3,
    createdAt: Date.now(),
  },
  {
    uid: 'cli5',
    username: 'cliente_final2',
    displayName: 'Maria Oliveira',
    role: 'client',
    clientType: 'final_client',
    status: 'approved',
    photoURL: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=150&h=150&auto=format&fit=crop',
    description: 'Buscando profissionais para manutenção preventiva.',
    rating: 4.7,
    reviewCount: 5,
    createdAt: Date.now(),
  }
];

export const MOCK_ADS: Ad[] = [
  {
    id: 'ad1',
    title: 'Construção de Muros e Calçadas',
    description: 'Mão de obra qualificada para construção de muros de arrimo, divisórios e calçadas em geral.',
    price: 150,
    category: 'Alvenaria e Estrutura',
    sellerId: 'pro1',
    sellerName: 'Carlos Alvenaria',
    sellerPhoto: 'https://images.pexels.com/photos/585419/pexels-photo-585419.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: { lat: -23.5505, lng: -46.6333, address: 'Centro, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    imageUrl: 'https://images.pexels.com/photos/159306/construction-site-build-construction-work-159306.jpeg?auto=compress&cs=tinysrgb&w=800',
    keywords: ['pedreiro', 'reforma', 'obra', 'muro', 'calcada', 'tijolo'],
  },
  {
    id: 'ad2',
    title: 'Instalação Elétrica Completa',
    description: 'Instalação de fiação, tomadas, interruptores e quadros de energia.',
    price: 2500,
    category: 'Elétrica',
    sellerId: 'pro2',
    sellerName: 'Ricardo Eletricista',
    sellerPhoto: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=150&h=150&auto=format&fit=crop',
    location: { lat: -23.5615, lng: -46.6553, address: 'Av. Paulista, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=800&h=600&auto=format&fit=crop',
    keywords: ['eletricista', 'fio', 'tomada', 'luz', 'energia', 'quadro', 'chuveiro'],
  },
  {
    id: 'ad3',
    title: 'Pintura Residencial Interna',
    description: 'Pintura de paredes e tetos com massa corrida e acabamento premium.',
    price: 1200,
    category: 'Pintura e Acabamento',
    sellerId: 'pro3',
    sellerName: 'Marcos Pinturas',
    sellerPhoto: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=150&h=150&auto=format&fit=crop',
    location: { lat: -23.5885, lng: -46.6783, address: 'Itaim Bibi, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
    imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=800&h=600&auto=format&fit=crop',
    keywords: ['pintor', 'reforma', 'acabamento', 'parede', 'tinta', 'massa corrida'],
  },
  {
    id: 'ad4',
    title: 'Forro de Drywall e Sancas',
    description: 'Instalação rápida de drywall, forros e sancas decorativas com iluminação embutida.',
    price: 85,
    category: 'Gesso e Drywall',
    sellerId: 'pro4',
    sellerName: 'Fabiano Gesseiro',
    sellerPhoto: 'https://images.unsplash.com/photo-1590650153855-d9e808231d41?q=80&w=150&h=150&auto=format&fit=crop',
    location: { lat: -23.5433, lng: -46.6433, address: 'República, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    imageUrl: 'https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?q=80&w=800&h=600&auto=format&fit=crop',
    keywords: ['gesseiro', 'forro', 'sanca', 'drywall', 'teto', 'decoracao'],
  },
  {
    id: 'ad5',
    title: 'Manutenção de Telhados e Calhas',
    description: 'Reparo de vazamentos, troca de telhas e limpeza completa de calhas e condutores.',
    price: 450,
    category: 'Telhados e Calhas',
    sellerId: 'pro6',
    sellerName: 'Sérgio Telhados',
    sellerPhoto: 'https://images.pexels.com/photos/1216589/pexels-photo-1216589.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: { lat: -23.6000, lng: -46.6750, address: 'Moema, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
    imageUrl: 'https://images.pexels.com/photos/3829227/pexels-photo-3829227.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 'ad6',
    title: 'Instalação de Porcelanato Grande Formato',
    description: 'Especialista em grandes formatos com junta mínima e acabamento de alto padrão.',
    price: 120,
    category: 'Pisos e Revestimentos',
    sellerId: 'pro7',
    sellerName: 'André Revestimentos',
    sellerPhoto: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=150&h=150&auto=format&fit=crop',
    location: { lat: -23.5700, lng: -46.6400, address: 'Paraíso, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&h=600&auto=format&fit=crop',
  },
  {
    id: 'ad7',
    title: 'Armários Planejados para Cozinha',
    description: 'Fabricação própria de móveis planejados em MDF com ferragens de primeira linha.',
    price: 5000,
    category: 'Marcenaria',
    sellerId: 'pro8',
    sellerName: 'Luiz Marceneiro',
    sellerPhoto: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=150&h=150&auto=format&fit=crop',
    location: { lat: -23.5200, lng: -46.7000, address: 'Lapa, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    imageUrl: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=800&h=600&auto=format&fit=crop',
  },
  {
    id: 'ad13',
    title: 'Portão Basculante Automático',
    description: 'Fabricação e instalação de portões basculantes em aço galvanizado com motor rápido.',
    price: 2800,
    category: 'Serralheria',
    sellerId: 'pro13',
    sellerName: 'Marcos Serralheiro',
    sellerPhoto: 'https://images.pexels.com/photos/2219024/pexels-photo-2219024.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: { lat: -23.5500, lng: -46.6500, address: 'Bela Vista, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    imageUrl: 'https://images.pexels.com/photos/2219024/pexels-photo-2219024.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 'ad14',
    title: 'Regularização de Imóvel e IPTU',
    description: 'Consultoria técnica para regularização de área construída, desmembramento e plantas.',
    price: 1500,
    category: 'Técnico de Edificação',
    sellerId: 'pro14',
    sellerName: 'Juliana Técnica',
    sellerPhoto: 'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: { lat: -23.5900, lng: -46.6800, address: 'Vila Olímpia, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    imageUrl: 'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 'ad8',
    title: 'Projeto de Interiores Residencial',
    description: 'Consultoria completa, plantas 3D e detalhamento técnico para sua reforma.',
    price: 3500,
    category: 'Arquitetura',
    sellerId: 'pro9',
    sellerName: 'Arq. Fernanda G.',
    sellerPhoto: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=150&h=150&auto=format&fit=crop',
    location: { lat: -23.5600, lng: -46.6600, address: 'Jardins, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 8,
    imageUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=800&h=600&auto=format&fit=crop',
  },
  {
    id: 'ad15',
    title: 'Cálculo Estrutural e ART',
    description: 'Elaboração de projetos estruturais, fundações e emissão de ART para obras residenciais.',
    price: 2500,
    category: 'Engenharia',
    sellerId: 'cli2', // Bruno Engenheiro
    sellerName: 'Bruno Engenheiro',
    sellerPhoto: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=150&h=150&auto=format&fit=crop',
    location: { lat: -23.5615, lng: -46.6553, address: 'Bela Vista, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
    imageUrl: 'https://images.unsplash.com/photo-1503387762-592dee58c460?q=80&w=800&h=600&auto=format&fit=crop',
  },
  {
    id: 'ad9',
    title: 'Limpeza Pós-Obra Profissional',
    description: 'Remoção de restos de cimento, tinta e limpeza fina para entrega das chaves.',
    price: 800,
    category: 'Limpeza Pós-Obra',
    sellerId: 'pro10',
    sellerName: 'Limpeza Brilho Total',
    sellerPhoto: 'https://images.unsplash.com/photo-1584820927498-cfe5211ff973?q=80&w=150&h=150&auto=format&fit=crop',
    location: { lat: -23.5300, lng: -46.6500, address: 'Santa Cecília, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 9,
    imageUrl: 'https://images.unsplash.com/photo-1584820927498-cfe5211ff973?q=80&w=800&h=600&auto=format&fit=crop',
  },
  {
    id: 'ad10',
    title: 'Marido de Aluguel - Reparos Gerais',
    description: 'Troca de chuveiro, instalação de prateleiras, conserto de torneiras e mais.',
    price: 120,
    category: 'Outros',
    sellerId: 'pro11',
    sellerName: 'Geraldo Faz-Tudo',
    sellerPhoto: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=150&h=150&auto=format&fit=crop',
    location: { lat: -23.5800, lng: -46.6300, address: 'Vila Mariana, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&h=600&auto=format&fit=crop',
  },
  {
    id: 'ad11',
    title: 'Instalação de Calhas e Rufos',
    description: 'Instalação de calhas de alumínio sem emenda e rufos para proteção de muros.',
    price: 65,
    category: 'Telhados e Calhas',
    sellerId: 'pro12',
    sellerName: 'Roberto Calhas',
    sellerPhoto: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: { lat: -23.5300, lng: -46.6800, address: 'Perdizes, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    imageUrl: 'https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 'ad12',
    title: 'Impermeabilização de Lajes e Telhados',
    description: 'Aplicação de manta asfáltica e resinas impermeabilizantes para acabar com infiltrações.',
    price: 850,
    category: 'Telhados e Calhas',
    sellerId: 'pro6',
    sellerName: 'Sérgio Telhados',
    sellerPhoto: 'https://images.pexels.com/photos/1216589/pexels-photo-1216589.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: { lat: -23.6100, lng: -46.6850, address: 'Campo Belo, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
    imageUrl: 'https://images.pexels.com/photos/2219024/pexels-photo-2219024.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 'ad16',
    title: 'Armação de Ferragens para Obra',
    description: 'Corte, dobra e montagem de ferragens para fundação e estrutura de concreto.',
    price: 180,
    category: 'Armador',
    sellerId: 'pro15',
    sellerName: 'Marcos Armador',
    sellerPhoto: 'https://images.pexels.com/photos/159306/construction-site-build-construction-work-159306.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: { lat: -23.5500, lng: -46.6300, address: 'Sé, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    imageUrl: 'https://images.pexels.com/photos/159306/construction-site-build-construction-work-159306.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 'ad17',
    title: 'Ajudante Geral para Obras',
    description: 'Mão de obra para auxílio geral em obras, transporte de materiais e organização do canteiro.',
    price: 100,
    category: 'Ajudante',
    sellerId: 'pro16',
    sellerName: 'Pedro Ajudante',
    sellerPhoto: 'https://images.pexels.com/photos/159358/construction-site-build-construction-work-159358.jpeg?auto=compress&cs=tinysrgb&w=150',
    location: { lat: -23.5600, lng: -46.6400, address: 'Liberdade, São Paulo - SP' },
    status: 'active',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
    imageUrl: 'https://images.pexels.com/photos/159358/construction-site-build-construction-work-159358.jpeg?auto=compress&cs=tinysrgb&w=800',
  }
];

export const MOCK_USER = MOCK_PROFESSIONALS[0];
